title: Markdown everyone
tagline: Mark everything down
description: If you want to mark stuff down, then this is the course for you.

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: electric-bugaloo
  repo: recipes

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: respond
  with: 01_first-response.md
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: Write a comment in an issue with a mention
- title: # the title of the step, shown to the learner in the course progress page
  description: # a description of the step, shown to the learner in the course progress page
  event: issue_comment.created
  actions:
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: Add name to README
    else:
    - type: respond
      with: 01_try-again.md
  - type: respond
    with: 01_nice-work.md
  
# Step 2: Use a header
# - title: # the title of the step, shown to the learner in the course progress page
#  description: # a description of the step, shown to the learner in the course progress page
#  event: issue_comment.created
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: Make a list
# - title: # the title of the step, shown to the learner in the course progress page
#  description: # a description of the step, shown to the learner in the course progress page
#  event: issue_comment.created
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: Include a URL
# - title: # the title of the step, shown to the learner in the course progress page
#  description: # a description of the step, shown to the learner in the course progress page
#  event: issue_comment.created
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: Include an image
# - title: # the title of the step, shown to the learner in the course progress page
#  description: # a description of the step, shown to the learner in the course progress page
#  event: issue_comment.created
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

